# Generated by Django 6.0.4 on 2026-04-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id_restaurante', models.CharField(help_text='ID único del restaurante', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del restaurante', max_length=100)),
                ('direccion', models.CharField(help_text='Dirección del local', max_length=150)),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=12)),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254)),
                ('tiempo_promedio_preparacion', models.PositiveSmallIntegerField(default=30, help_text='Tiempo en minutos')),
                ('activo', models.BooleanField(default=True, help_text='Si el restaurante está disponible')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.CharField(help_text='ID único del plato', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del plato', max_length=100)),
                ('descripcion', models.CharField(help_text='Descripción detallada del plato', max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en pesos chilenos', max_digits=8)),
                ('tiempo_preparacion', models.PositiveSmallIntegerField(default=15, help_text='Tiempo en minutos')),
                ('ingredientes', models.CharField(help_text='Ingredientes principales (separados por coma)', max_length=200)),
                ('disponible', models.BooleanField(default=True, help_text='Si el plato está disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='Restaurantes.restaurante')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'unique_together': {('restaurante', 'nombre')},
            },
        ),
    ]
